apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: troll-kokken
  namespace: n415-retreat
spec:
  image: {{ image }}
  ingresses: 
  - "https://troll-kokken.ekstern.dev.nav.no"
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi 
  accessPolicy:
    outbound:
      rules:
        - application: "troll-gryta"
